#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Nov 22, 2021 05:22:45 PM +07  platform: Windows NT
set vTcl(timestamp) ""


set image_list { \
    angga_png "../../../Users/Risfanani/Desktop/angga.png" \
    arya_png "../../../Users/Risfanani/Desktop/arya.png" \
    zaim_png "../../../Users/Risfanani/Desktop/zaim.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #ffffff
set vTcl(pr,menuanalogcolor) #ffffff
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 800x600+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Digital Signature"
    vTcl:DefineAlias "$top" "mainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Zorque} -size 24} -foreground $vTcl(actual_gui_fg) \
        -text {DIGITAL SIGNATURE} 
    vTcl:DefineAlias "$top.lab44" "titleLabel" vTcl:WidgetProc "mainWindow" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Generate Private Key} 
    vTcl:DefineAlias "$top.but45" "genPriKeyButton" vTcl:WidgetProc "mainWindow" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Generate Public Key} 
    vTcl:DefineAlias "$top.but46" "genPubKeyButton" vTcl:WidgetProc "mainWindow" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Sign Document(txt)} 
    vTcl:DefineAlias "$top.but47" "signButton" vTcl:WidgetProc "mainWindow" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Verify Document(txt)} 
    vTcl:DefineAlias "$top.but48" "verifyButton" vTcl:WidgetProc "mainWindow" 1
    label $top.lab50 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text {Generate your RSA key here!} 
    vTcl:DefineAlias "$top.lab50" "subtitle1Label" vTcl:WidgetProc "mainWindow" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -text {Put your signature or Verify signed document here} 
    vTcl:DefineAlias "$top.lab51" "subtitle2Label" vTcl:WidgetProc "mainWindow" 1
    label $top.lab54 \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -image zaim_png -text Label 
    vTcl:DefineAlias "$top.lab54" "zaimImg" vTcl:WidgetProc "mainWindow" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -image angga_png -text Label 
    vTcl:DefineAlias "$top.lab55" "anggaImg" vTcl:WidgetProc "mainWindow" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -image arya_png -text Label 
    vTcl:DefineAlias "$top.lab56" "aryaImg" vTcl:WidgetProc "mainWindow" 1
    label $top.lab57 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -text {Status: App succesfully opened} 
    vTcl:DefineAlias "$top.lab57" "statusLabel" vTcl:WidgetProc "mainWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.017 -width 0 -relwidth 0.974 \
        -height 0 -relheight 0.227 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.35 -width 150 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.513 -y 0 -rely 0.35 -width 150 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.533 -width 175 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.6 -width 175 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.283 -width 0 -relwidth 0.406 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.263 -y 0 -rely 0.467 -width 0 -relwidth 0.483 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.275 -y 0 -rely 0.783 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.227 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.6 -y 0 -rely 0.783 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.227 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.438 -y 0 -rely 0.783 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.227 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.125 -y 0 -rely 0.667 -width 0 -relwidth 0.765 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

