#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Nov 22, 2021 05:31:04 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import page.menu as menu
import digital_signature as ds
import easygui
import start

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def backToMenuWindow():
    destroy_window()
    menu.vp_start_gui()

def openFile():
    return easygui.fileopenbox(title='Select File (.txt)')

def tapInsert():
    path = openFile()
    if (path != None):
        if (start.SorV == "S"):
            f = open('./key/rsa.pri', 'r')
            S = ds.make_digital_signature(path, int(float(f.read().split(" ")[0])), start.p*start.q)
            ds.add_digital_signature(S, path)
            f.close()
            start.status = "Status: Document succesfully signed to " + path.split('\\')[-1]
        elif (start.SorV == "V"):
            f = open('./key/rsa.pub', 'r')
            start.status = "Status: " + ds.verification_ds(path, path, int(f.read().split(" ")[0]), start.p*start.q, "Yes")
            f.close()
        else:
            return
        backToMenuWindow()

def tapSeparate():
    path = openFile()
    if (path != None):
        if (start.SorV == "S"):
            True
        elif (start.SorV == "V"):
            True
        else:
            return
        backToMenuWindow()